=== NazBor-Cod/itstep/HW_13_Virtual_Functions/Example_CS_XML/academy.dtd
<!ELEMENT academy (students, subjects)>

<!ELEMENT students (student*)>

<!ELEMENT student (marks)>

<!ATTLIST student
  firstName CDATA #REQUIRED
  lastName CDATA #REQUIRED
  middleName CDATA #IMPLIED
  age CDATA #IMPLIED
>

<!ELEMENT subjects (subject*)>
<!ELEMENT subject EMPTY>

<!ATTLIST subject
  name ID #REQUIRED
>

<!ELEMENT marks (mark*)>

<!ELEMENT mark EMPTY>

<!ATTLIST mark
  subject IDREF #REQUIRED
  value (1|2|3|4|5|6|7|8|9|10|11|12) #REQUIRED
>

=== NazBor-Cod/itstep/HW_13_Virtual_Functions/Example_CS_XML/academy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE academy SYSTEM "./academy.dtd"[]>
<academy xmlns="./academy.xsd">
  <students>
    <student firstName="Vasa" lastName="Pupkin">
      <marks>
        <mark subject="CS" value="12" />
        <mark subject="CPP" value="12" />
        <mark subject="MSP" value="12" />
        <mark subject="SQL" value="10" />
      </marks>
    </student>
    <student firstName="Oleg" lastName="Petrov">
      <marks>
        <mark subject="CS" value="12" />
        <mark subject="CPP" value="12" />
        <mark subject="MSP" value="12" />
        <mark subject="SQL" value="10" />
      </marks>
    </student>
    <student firstName="Федя" lastName="Сидоров">
      <marks>
        <mark subject="CS" value="1" />
        <mark subject="CPP" value="12" />
        <mark subject="MSP" value="12" />
        <mark subject="SQL" value="10" />
      </marks>
    </student>
  </students>
  <subjects>
    <subject name="CS" />
    <subject name="CPP" />
    <subject name="SQL" />
    <subject name="MSP" />
  </subjects>
</academy>
